// AUTO-GENERATED by src/tools/extract-hardware.ts — DO NOT EDIT BY HAND.
// Run `npx tsx src/tools/extract-hardware.ts` to regenerate.
//
// The owner's real supplier stock list (collections/part-list/stockitems.json),
// restricted to the sub-categories the engine substitutes 1:1 — casement
// handles, door handles, cylinders, door hinges, door locks. Merged into
// SUNNYPLAST_70.hardware by system-sunnyplast.ts, AFTER the hand-written
// entries, so a calibrated key always wins.
//
// cost / price / weight are 0 — no supplier price is guessed (golden rule); the
// owner fills them via the admin catalog CRUD / CSV import. No `lengthMm`, so
// the size-selecting pickers can never choose one of these. No design
// references them and no cut rule emits them, so every quote is unchanged.
//
// CODES: verbatim from the stock list where it has one (cylinders). Handles,
// hinges and locks export a BLANK code, so theirs are SYNTHESIZED from the part
// name — same convention as the hand-written HDL-INLINE / DR-HDL-LL / FH-90DEG.
// Reconcile against an authentic supplier code list before ordering from them.
import type { HardwareItem } from "../types.ts";

export const STOCK_HARDWARE: Record<string, HardwareItem> = {
  "hw-cylinder-brass-keyed-alike": {
    "code": "GBCKA1",
    "name": "Brass Cylinder Keyed Alike",
    "cost": 0,
    "price": 0,
    "per": "pc",
    "weight": 0,
    "financialCategory": "Cylinders"
  },
  "hw-cylinder-brass-thumbturn": {
    "code": "GBCT1",
    "name": "Brass Cylinder Thumbturn",
    "cost": 0,
    "price": 0,
    "per": "pc",
    "weight": 0,
    "financialCategory": "Cylinders"
  },
  "hw-cylinder-brass-thumbturn-alike": {
    "code": "GBCTKA1",
    "name": "Brass Cylinder Thumbturn Alike",
    "cost": 0,
    "price": 0,
    "per": "pc",
    "weight": 0,
    "financialCategory": "Cylinders"
  },
  "hw-cylinder-high-security-brass": {
    "code": "GHSBC1",
    "name": "High Security Brass Cylinder",
    "cost": 0,
    "price": 0,
    "per": "pc",
    "weight": 0,
    "financialCategory": "Cylinders"
  },
  "hw-cylinder-high-security-brass-thumbturn": {
    "code": "GHSBCT1",
    "name": "High Security Brass Cylinder Thumbturn",
    "cost": 0,
    "price": 0,
    "per": "pc",
    "weight": 0,
    "financialCategory": "Cylinders"
  },
  "hw-cylinder-high-security-nickel": {
    "code": "GHSNC1",
    "name": "High Security Nickel Cylinder",
    "cost": 0,
    "price": 0,
    "per": "pc",
    "weight": 0,
    "financialCategory": "Cylinders"
  },
  "hw-cylinder-high-security-nickel-thumbturn": {
    "code": "GHSNCT1",
    "name": "High Security Nickel Cylinder Thumbturn",
    "cost": 0,
    "price": 0,
    "per": "pc",
    "weight": 0,
    "financialCategory": "Cylinders"
  },
  "hw-cylinder-nickel": {
    "code": "GNC1",
    "name": "Nickel Cylinder",
    "cost": 0,
    "price": 0,
    "per": "pc",
    "weight": 0,
    "financialCategory": "Cylinders"
  },
  "hw-cylinder-nickel-keyed-alike": {
    "code": "GNCKA1",
    "name": "Nickel Cylinder Keyed Alike",
    "cost": 0,
    "price": 0,
    "per": "pc",
    "weight": 0,
    "financialCategory": "Cylinders"
  },
  "hw-cylinder-nickel-thumbturn": {
    "code": "GNCT1",
    "name": "Nickel Cylinder Thumbturn",
    "cost": 0,
    "price": 0,
    "per": "pc",
    "weight": 0,
    "financialCategory": "Cylinders"
  },
  "hw-cylinder-nickel-thumbturn-alike": {
    "code": "GNCTKA1",
    "name": "Nickel Cylinder Thumbturn Alike",
    "cost": 0,
    "price": 0,
    "per": "pc",
    "weight": 0,
    "financialCategory": "Cylinders"
  },
  "hw-cylinder-yale-3-platinum-35-35": {
    "code": "9417N",
    "name": "Yale 3* Platinum 35/35 Cylinder",
    "cost": 0,
    "price": 0,
    "per": "pc",
    "weight": 0,
    "financialCategory": "Cylinders"
  },
  "hw-cylinder-yale-3-platinum-45-55": {
    "code": "9416N",
    "name": "Yale 3* Platinum 45/55 Cylinder",
    "cost": 0,
    "price": 0,
    "per": "pc",
    "weight": 0,
    "financialCategory": "Cylinders"
  },
  "hw-cylinder-yale-3-platinum-55-45": {
    "code": "9418N",
    "name": "Yale 3* Platinum 55/45 Cylinder",
    "cost": 0,
    "price": 0,
    "per": "pc",
    "weight": 0,
    "financialCategory": "Cylinders"
  },
  "hw-door-handle-bar-1000-inline": {
    "code": "DR-HDL-BAR-1000-INLINE",
    "name": "Bar Handle 1000 Inline",
    "cost": 0,
    "price": 0,
    "per": "pc",
    "weight": 0,
    "financialCategory": "Door Handle"
  },
  "hw-door-handle-bar-1000-offset": {
    "code": "DR-HDL-BAR-1000-OFFSET",
    "name": "Bar Handle 1000 Offset",
    "cost": 0,
    "price": 0,
    "per": "pc",
    "weight": 0,
    "financialCategory": "Door Handle"
  },
  "hw-door-handle-bar-1200-inline": {
    "code": "DR-HDL-BAR-1200-INLINE",
    "name": "Bar Handle 1200 Inline",
    "cost": 0,
    "price": 0,
    "per": "pc",
    "weight": 0,
    "financialCategory": "Door Handle"
  },
  "hw-door-handle-bar-1200-offset": {
    "code": "DR-HDL-BAR-1200-OFFSET",
    "name": "Bar Handle 1200 Offset",
    "cost": 0,
    "price": 0,
    "per": "pc",
    "weight": 0,
    "financialCategory": "Door Handle"
  },
  "hw-door-handle-bar-1400-inline": {
    "code": "DR-HDL-BAR-1400-INLINE",
    "name": "Bar Handle 1400 Inline",
    "cost": 0,
    "price": 0,
    "per": "pc",
    "weight": 0,
    "financialCategory": "Door Handle"
  },
  "hw-door-handle-bar-1400-offset": {
    "code": "DR-HDL-BAR-1400-OFFSET",
    "name": "Bar Handle 1400 Offset",
    "cost": 0,
    "price": 0,
    "per": "pc",
    "weight": 0,
    "financialCategory": "Door Handle"
  },
  "hw-door-handle-bar-1600-inline": {
    "code": "DR-HDL-BAR-1600-INLINE",
    "name": "Bar Handle 1600 Inline",
    "cost": 0,
    "price": 0,
    "per": "pc",
    "weight": 0,
    "financialCategory": "Door Handle"
  },
  "hw-door-handle-bar-1600-offset": {
    "code": "DR-HDL-BAR-1600-OFFSET",
    "name": "Bar Handle 1600 Offset",
    "cost": 0,
    "price": 0,
    "per": "pc",
    "weight": 0,
    "financialCategory": "Door Handle"
  },
  "hw-door-handle-bar-1800-inline": {
    "code": "DR-HDL-BAR-1800-INLINE",
    "name": "Bar Handle 1800 Inline",
    "cost": 0,
    "price": 0,
    "per": "pc",
    "weight": 0,
    "financialCategory": "Door Handle"
  },
  "hw-door-handle-bar-1800-offset": {
    "code": "DR-HDL-BAR-1800-OFFSET",
    "name": "Bar Handle 1800 Offset",
    "cost": 0,
    "price": 0,
    "per": "pc",
    "weight": 0,
    "financialCategory": "Door Handle"
  },
  "hw-door-handle-bar-400-offset": {
    "code": "DR-HDL-BAR-400-OFFSET",
    "name": "Bar Handle 400 Offset",
    "cost": 0,
    "price": 0,
    "per": "pc",
    "weight": 0,
    "financialCategory": "Door Handle"
  },
  "hw-door-handle-bar-600-inline": {
    "code": "DR-HDL-BAR-600-INLINE",
    "name": "Bar Handle 600 Inline",
    "cost": 0,
    "price": 0,
    "per": "pc",
    "weight": 0,
    "financialCategory": "Door Handle"
  },
  "hw-door-handle-bar-600-offset": {
    "code": "DR-HDL-BAR-600-OFFSET",
    "name": "Bar Handle 600 Offset",
    "cost": 0,
    "price": 0,
    "per": "pc",
    "weight": 0,
    "financialCategory": "Door Handle"
  },
  "hw-door-handle-bar-800-inline": {
    "code": "DR-HDL-BAR-800-INLINE",
    "name": "Bar Handle 800 Inline",
    "cost": 0,
    "price": 0,
    "per": "pc",
    "weight": 0,
    "financialCategory": "Door Handle"
  },
  "hw-door-handle-bar-800-offset": {
    "code": "DR-HDL-BAR-800-OFFSET",
    "name": "Bar Handle 800 Offset",
    "cost": 0,
    "price": 0,
    "per": "pc",
    "weight": 0,
    "financialCategory": "Door Handle"
  },
  "hw-door-handle-bar-bow": {
    "code": "DR-HDL-BAR-BOW",
    "name": "Bar Handle Bow",
    "cost": 0,
    "price": 0,
    "per": "pc",
    "weight": 0,
    "financialCategory": "Door Handle"
  },
  "hw-door-handle-bar-d-shape": {
    "code": "DR-HDL-BAR-D-SHAPE",
    "name": "Bar Handle D Shape",
    "cost": 0,
    "price": 0,
    "per": "pc",
    "weight": 0,
    "financialCategory": "Door Handle"
  },
  "hw-door-handle-bar-v-shape": {
    "code": "DR-HDL-BAR-V-SHAPE",
    "name": "Bar Handle V Shape",
    "cost": 0,
    "price": 0,
    "per": "pc",
    "weight": 0,
    "financialCategory": "Door Handle"
  },
  "hw-door-handle-black-lever-lever-long-backplate": {
    "code": "DR-HDL-BLACK-LEVER-LEVER-LONG-BACKPLATE",
    "name": "Black Handle Lever/Lever (Long Backplate)",
    "cost": 0,
    "price": 0,
    "per": "pc",
    "weight": 0,
    "financialCategory": "Door Handle"
  },
  "hw-door-handle-black-lever-lever-short-backplate": {
    "code": "DR-HDL-BLACK-LEVER-LEVER-SHORT-BACKPLATE",
    "name": "Black Handle Lever/Lever (Short Backplate)",
    "cost": 0,
    "price": 0,
    "per": "pc",
    "weight": 0,
    "financialCategory": "Door Handle"
  },
  "hw-door-handle-black-lever-pad-long-backplate": {
    "code": "DR-HDL-BLACK-LEVER-PAD-LONG-BACKPLATE",
    "name": "Black Handle Lever/Pad (Long Backplate)",
    "cost": 0,
    "price": 0,
    "per": "pc",
    "weight": 0,
    "financialCategory": "Door Handle"
  },
  "hw-door-handle-black-lever-pad-short-backplate": {
    "code": "DR-HDL-BLACK-LEVER-PAD-SHORT-BACKPLATE",
    "name": "Black Handle Lever/Pad (Short Backplate)",
    "cost": 0,
    "price": 0,
    "per": "pc",
    "weight": 0,
    "financialCategory": "Door Handle"
  },
  "hw-door-handle-bronze-lever-lever-long-backplate": {
    "code": "DR-HDL-BRONZE-LEVER-LEVER-LONG-BACKPLATE",
    "name": "Bronze Handle Lever/Lever (Long Backplate)",
    "cost": 0,
    "price": 0,
    "per": "pc",
    "weight": 0,
    "financialCategory": "Door Handle"
  },
  "hw-door-handle-bronze-lever-lever-short-backplate": {
    "code": "DR-HDL-BRONZE-LEVER-LEVER-SHORT-BACKPLATE",
    "name": "Bronze Handle Lever/Lever (Short Backplate)",
    "cost": 0,
    "price": 0,
    "per": "pc",
    "weight": 0,
    "financialCategory": "Door Handle"
  },
  "hw-door-handle-bronze-lever-pad-long-backplate": {
    "code": "DR-HDL-BRONZE-LEVER-PAD-LONG-BACKPLATE",
    "name": "Bronze Handle Lever/Pad (Long Backplate)",
    "cost": 0,
    "price": 0,
    "per": "pc",
    "weight": 0,
    "financialCategory": "Door Handle"
  },
  "hw-door-handle-bronze-lever-pad-short-backplate": {
    "code": "DR-HDL-BRONZE-LEVER-PAD-SHORT-BACKPLATE",
    "name": "Bronze Handle Lever/Pad (Short Backplate)",
    "cost": 0,
    "price": 0,
    "per": "pc",
    "weight": 0,
    "financialCategory": "Door Handle"
  },
  "hw-door-handle-chrome-lever-lever-long-backplate": {
    "code": "DR-HDL-CHROME-LEVER-LEVER-LONG-BACKPLATE",
    "name": "Chrome Handle Lever/Lever (Long Backplate)",
    "cost": 0,
    "price": 0,
    "per": "pc",
    "weight": 0,
    "financialCategory": "Door Handle"
  },
  "hw-door-handle-chrome-lever-lever-short-backplate": {
    "code": "DR-HDL-CHROME-LEVER-LEVER-SHORT-BACKPLATE",
    "name": "Chrome Handle Lever/Lever (Short Backplate)",
    "cost": 0,
    "price": 0,
    "per": "pc",
    "weight": 0,
    "financialCategory": "Door Handle"
  },
  "hw-door-handle-chrome-lever-pad-long-backplate": {
    "code": "DR-HDL-CHROME-LEVER-PAD-LONG-BACKPLATE",
    "name": "Chrome Handle Lever/Pad (Long Backplate)",
    "cost": 0,
    "price": 0,
    "per": "pc",
    "weight": 0,
    "financialCategory": "Door Handle"
  },
  "hw-door-handle-chrome-lever-pad-short-backplate": {
    "code": "DR-HDL-CHROME-LEVER-PAD-SHORT-BACKPLATE",
    "name": "Chrome Handle Lever/Pad (Short Backplate)",
    "cost": 0,
    "price": 0,
    "per": "pc",
    "weight": 0,
    "financialCategory": "Door Handle"
  },
  "hw-door-handle-gold-lever-lever-long-backplate": {
    "code": "DR-HDL-GOLD-LEVER-LEVER-LONG-BACKPLATE",
    "name": "Gold Handle Lever/Lever (Long Backplate)",
    "cost": 0,
    "price": 0,
    "per": "pc",
    "weight": 0,
    "financialCategory": "Door Handle"
  },
  "hw-door-handle-gold-lever-lever-short-backplate": {
    "code": "DR-HDL-GOLD-LEVER-LEVER-SHORT-BACKPLATE",
    "name": "Gold Handle Lever/Lever (Short Backplate)",
    "cost": 0,
    "price": 0,
    "per": "pc",
    "weight": 0,
    "financialCategory": "Door Handle"
  },
  "hw-door-handle-gold-lever-pad-long-backplate": {
    "code": "DR-HDL-GOLD-LEVER-PAD-LONG-BACKPLATE",
    "name": "Gold Handle Lever/Pad (Long Backplate)",
    "cost": 0,
    "price": 0,
    "per": "pc",
    "weight": 0,
    "financialCategory": "Door Handle"
  },
  "hw-door-handle-gold-lever-pad-short-backplate": {
    "code": "DR-HDL-GOLD-LEVER-PAD-SHORT-BACKPLATE",
    "name": "Gold Handle Lever/Pad (Short Backplate)",
    "cost": 0,
    "price": 0,
    "per": "pc",
    "weight": 0,
    "financialCategory": "Door Handle"
  },
  "hw-door-handle-graphite-lever-lever-long-backplate": {
    "code": "DR-HDL-GRAPHITE-LEVER-LEVER-LONG-BACKPLATE",
    "name": "Graphite Handle Lever/Lever (Long Backplate)",
    "cost": 0,
    "price": 0,
    "per": "pc",
    "weight": 0,
    "financialCategory": "Door Handle"
  },
  "hw-door-handle-graphite-lever-lever-short-backplate": {
    "code": "DR-HDL-GRAPHITE-LEVER-LEVER-SHORT-BACKPLATE",
    "name": "Graphite Handle Lever/Lever (Short Backplate)",
    "cost": 0,
    "price": 0,
    "per": "pc",
    "weight": 0,
    "financialCategory": "Door Handle"
  },
  "hw-door-handle-graphite-lever-pad-long-backplate": {
    "code": "DR-HDL-GRAPHITE-LEVER-PAD-LONG-BACKPLATE",
    "name": "Graphite Handle Lever/Pad (Long Backplate)",
    "cost": 0,
    "price": 0,
    "per": "pc",
    "weight": 0,
    "financialCategory": "Door Handle"
  },
  "hw-door-handle-graphite-lever-pad-short-backplate": {
    "code": "DR-HDL-GRAPHITE-LEVER-PAD-SHORT-BACKPLATE",
    "name": "Graphite Handle Lever/Pad (Short Backplate)",
    "cost": 0,
    "price": 0,
    "per": "pc",
    "weight": 0,
    "financialCategory": "Door Handle"
  },
  "hw-door-handle-panic-bar-int-ext-access": {
    "code": "DR-HDL-PANIC-BAR-INT-EXT-ACCESS",
    "name": "Panic Bar Int/Ext Access",
    "cost": 0,
    "price": 0,
    "per": "pc",
    "weight": 0,
    "financialCategory": "Door Handle"
  },
  "hw-door-handle-panic-bar-internal-access": {
    "code": "DR-HDL-PANIC-BAR-INTERNAL-ACCESS",
    "name": "Panic Bar Internal Access",
    "cost": 0,
    "price": 0,
    "per": "pc",
    "weight": 0,
    "financialCategory": "Door Handle"
  },
  "hw-door-handle-panic-pad-int-ext-access": {
    "code": "DR-HDL-PANIC-PAD-INT-EXT-ACCESS",
    "name": "Panic Pad Int/Ext Access",
    "cost": 0,
    "price": 0,
    "per": "pc",
    "weight": 0,
    "financialCategory": "Door Handle"
  },
  "hw-door-handle-panic-pad-internal-access": {
    "code": "DR-HDL-PANIC-PAD-INTERNAL-ACCESS",
    "name": "Panic Pad Internal Access",
    "cost": 0,
    "price": 0,
    "per": "pc",
    "weight": 0,
    "financialCategory": "Door Handle"
  },
  "hw-door-handle-silver-lever-lever-long-backplate": {
    "code": "DR-HDL-SILVER-LEVER-LEVER-LONG-BACKPLATE",
    "name": "Silver Handle Lever/Lever (Long Backplate)",
    "cost": 0,
    "price": 0,
    "per": "pc",
    "weight": 0,
    "financialCategory": "Door Handle"
  },
  "hw-door-handle-silver-lever-lever-short-backplate": {
    "code": "DR-HDL-SILVER-LEVER-LEVER-SHORT-BACKPLATE",
    "name": "Silver Handle Lever/Lever (Short Backplate)",
    "cost": 0,
    "price": 0,
    "per": "pc",
    "weight": 0,
    "financialCategory": "Door Handle"
  },
  "hw-door-handle-silver-lever-pad-long-backplate": {
    "code": "DR-HDL-SILVER-LEVER-PAD-LONG-BACKPLATE",
    "name": "Silver Handle Lever/Pad (Long Backplate)",
    "cost": 0,
    "price": 0,
    "per": "pc",
    "weight": 0,
    "financialCategory": "Door Handle"
  },
  "hw-door-handle-silver-lever-pad-short-backplate": {
    "code": "DR-HDL-SILVER-LEVER-PAD-SHORT-BACKPLATE",
    "name": "Silver Handle Lever/Pad (Short Backplate)",
    "cost": 0,
    "price": 0,
    "per": "pc",
    "weight": 0,
    "financialCategory": "Door Handle"
  },
  "hw-door-handle-stainless-steel-lever-lever-long-backplate": {
    "code": "DR-HDL-STAINLESS-STEEL-LEVER-LEVER-LONG-BACKPLATE",
    "name": "Stainless Steel Handle Lever/Lever (Long Backplate)",
    "cost": 0,
    "price": 0,
    "per": "pc",
    "weight": 0,
    "financialCategory": "Door Handle"
  },
  "hw-door-handle-stainless-steel-lever-lever-short-backplate": {
    "code": "DR-HDL-STAINLESS-STEEL-LEVER-LEVER-SHORT-BACKPLATE",
    "name": "Stainless Steel Handle Lever/Lever (Short Backplate)",
    "cost": 0,
    "price": 0,
    "per": "pc",
    "weight": 0,
    "financialCategory": "Door Handle"
  },
  "hw-door-handle-stainless-steel-lever-pad-long-backplate": {
    "code": "DR-HDL-STAINLESS-STEEL-LEVER-PAD-LONG-BACKPLATE",
    "name": "Stainless Steel Handle Lever/Pad (Long Backplate)",
    "cost": 0,
    "price": 0,
    "per": "pc",
    "weight": 0,
    "financialCategory": "Door Handle"
  },
  "hw-door-handle-stainless-steel-lever-pad-short-backplate": {
    "code": "DR-HDL-STAINLESS-STEEL-LEVER-PAD-SHORT-BACKPLATE",
    "name": "Stainless Steel Handle Lever/Pad (Short Backplate)",
    "cost": 0,
    "price": 0,
    "per": "pc",
    "weight": 0,
    "financialCategory": "Door Handle"
  },
  "hw-door-handle-white-lever-lever-long-backplate": {
    "code": "DR-HDL-WHITE-LEVER-LEVER-LONG-BACKPLATE",
    "name": "White Handle Lever/Lever (Long Backplate)",
    "cost": 0,
    "price": 0,
    "per": "pc",
    "weight": 0,
    "financialCategory": "Door Handle"
  },
  "hw-door-handle-white-lever-pad-long-backplate": {
    "code": "DR-HDL-WHITE-LEVER-PAD-LONG-BACKPLATE",
    "name": "White Handle Lever/Pad (Long Backplate)",
    "cost": 0,
    "price": 0,
    "per": "pc",
    "weight": 0,
    "financialCategory": "Door Handle"
  },
  "hw-door-handle-white-lever-pad-short-backplate": {
    "code": "DR-HDL-WHITE-LEVER-PAD-SHORT-BACKPLATE",
    "name": "White Handle Lever/Pad (Short Backplate)",
    "cost": 0,
    "price": 0,
    "per": "pc",
    "weight": 0,
    "financialCategory": "Door Handle"
  },
  "hw-door-hinge-flag-black": {
    "code": "DR-HNG-FLAG-BLACK",
    "name": "Flag Hinge Black",
    "cost": 0,
    "price": 0,
    "per": "pc",
    "weight": 0,
    "financialCategory": "Door Hinge"
  },
  "hw-door-hinge-flag-bronze": {
    "code": "DR-HNG-FLAG-BRONZE",
    "name": "Flag Hinge Bronze",
    "cost": 0,
    "price": 0,
    "per": "pc",
    "weight": 0,
    "financialCategory": "Door Hinge"
  },
  "hw-door-hinge-flag-brown": {
    "code": "DR-HNG-FLAG-BROWN",
    "name": "Flag Hinge Brown",
    "cost": 0,
    "price": 0,
    "per": "pc",
    "weight": 0,
    "financialCategory": "Door Hinge"
  },
  "hw-door-hinge-flag-chrome": {
    "code": "DR-HNG-FLAG-CHROME",
    "name": "Flag Hinge Chrome",
    "cost": 0,
    "price": 0,
    "per": "pc",
    "weight": 0,
    "financialCategory": "Door Hinge"
  },
  "hw-door-hinge-flag-gold": {
    "code": "DR-HNG-FLAG-GOLD",
    "name": "Flag Hinge Gold",
    "cost": 0,
    "price": 0,
    "per": "pc",
    "weight": 0,
    "financialCategory": "Door Hinge"
  },
  "hw-door-hinge-flag-graphite": {
    "code": "DR-HNG-FLAG-GRAPHITE",
    "name": "Flag Hinge Graphite",
    "cost": 0,
    "price": 0,
    "per": "pc",
    "weight": 0,
    "financialCategory": "Door Hinge"
  },
  "hw-door-hinge-flag-satin": {
    "code": "DR-HNG-FLAG-SATIN",
    "name": "Flag Hinge Satin",
    "cost": 0,
    "price": 0,
    "per": "pc",
    "weight": 0,
    "financialCategory": "Door Hinge"
  },
  "hw-door-hinge-flag-silver": {
    "code": "DR-HNG-FLAG-SILVER",
    "name": "Flag Hinge Silver",
    "cost": 0,
    "price": 0,
    "per": "pc",
    "weight": 0,
    "financialCategory": "Door Hinge"
  },
  "hw-door-hinge-high-security-black": {
    "code": "DR-HNG-HIGH-SECURITY-BLACK",
    "name": "High Security Hinge Black",
    "cost": 0,
    "price": 0,
    "per": "pc",
    "weight": 0,
    "financialCategory": "Door Hinge"
  },
  "hw-door-hinge-high-security-bronze": {
    "code": "DR-HNG-HIGH-SECURITY-BRONZE",
    "name": "High Security Hinge Bronze",
    "cost": 0,
    "price": 0,
    "per": "pc",
    "weight": 0,
    "financialCategory": "Door Hinge"
  },
  "hw-door-hinge-high-security-brown": {
    "code": "DR-HNG-HIGH-SECURITY-BROWN",
    "name": "High Security Hinge Brown",
    "cost": 0,
    "price": 0,
    "per": "pc",
    "weight": 0,
    "financialCategory": "Door Hinge"
  },
  "hw-door-hinge-high-security-chrome": {
    "code": "DR-HNG-HIGH-SECURITY-CHROME",
    "name": "High Security Hinge Chrome",
    "cost": 0,
    "price": 0,
    "per": "pc",
    "weight": 0,
    "financialCategory": "Door Hinge"
  },
  "hw-door-hinge-high-security-gold": {
    "code": "DR-HNG-HIGH-SECURITY-GOLD",
    "name": "High Security Hinge Gold",
    "cost": 0,
    "price": 0,
    "per": "pc",
    "weight": 0,
    "financialCategory": "Door Hinge"
  },
  "hw-door-hinge-high-security-graphite": {
    "code": "DR-HNG-HIGH-SECURITY-GRAPHITE",
    "name": "High Security Hinge Graphite",
    "cost": 0,
    "price": 0,
    "per": "pc",
    "weight": 0,
    "financialCategory": "Door Hinge"
  },
  "hw-door-hinge-high-security-satin": {
    "code": "DR-HNG-HIGH-SECURITY-SATIN",
    "name": "High Security Hinge Satin",
    "cost": 0,
    "price": 0,
    "per": "pc",
    "weight": 0,
    "financialCategory": "Door Hinge"
  },
  "hw-door-hinge-high-security-silver": {
    "code": "DR-HNG-HIGH-SECURITY-SILVER",
    "name": "High Security Hinge Silver",
    "cost": 0,
    "price": 0,
    "per": "pc",
    "weight": 0,
    "financialCategory": "Door Hinge"
  },
  "hw-door-hinge-high-security-white": {
    "code": "DR-HNG-HIGH-SECURITY-WHITE",
    "name": "High Security Hinge White",
    "cost": 0,
    "price": 0,
    "per": "pc",
    "weight": 0,
    "financialCategory": "Door Hinge"
  },
  "hw-door-lock-double-shootbolt-keep-set": {
    "code": "DR-LCK-DOUBLE-SHOOTBOLT-KEEP-SET",
    "name": "Double Shootbolt Keep Set",
    "cost": 0,
    "price": 0,
    "per": "pc",
    "weight": 0,
    "financialCategory": "Door Lock"
  },
  "hw-door-lock-fingerbolt-set": {
    "code": "DR-LCK-FINGERBOLT-SET",
    "name": "Fingerbolt Set",
    "cost": 0,
    "price": 0,
    "per": "pc",
    "weight": 0,
    "financialCategory": "Door Lock"
  },
  "hw-door-lock-high-security-door": {
    "code": "DR-LCK-HIGH-SECURITY-DOOR",
    "name": "High Security Door Lock",
    "cost": 0,
    "price": 0,
    "per": "pc",
    "weight": 0,
    "financialCategory": "Door Lock"
  },
  "hw-door-lock-high-security-slave-door": {
    "code": "DR-LCK-HIGH-SECURITY-SLAVE-DOOR",
    "name": "High Security Slave Door Lock",
    "cost": 0,
    "price": 0,
    "per": "pc",
    "weight": 0,
    "financialCategory": "Door Lock"
  },
  "hw-door-lock-shootbolt-door": {
    "code": "DR-LCK-SHOOTBOLT-DOOR",
    "name": "Shootbolt Door Lock",
    "cost": 0,
    "price": 0,
    "per": "pc",
    "weight": 0,
    "financialCategory": "Door Lock"
  },
  "hw-door-lock-shootbolt-slave-door": {
    "code": "DR-LCK-SHOOTBOLT-SLAVE-DOOR",
    "name": "Shootbolt Slave Door Lock",
    "cost": 0,
    "price": 0,
    "per": "pc",
    "weight": 0,
    "financialCategory": "Door Lock"
  },
  "hw-door-lock-single-shootbolt-keep-set": {
    "code": "DR-LCK-SINGLE-SHOOTBOLT-KEEP-SET",
    "name": "Single Shootbolt Keep Set",
    "cost": 0,
    "price": 0,
    "per": "pc",
    "weight": 0,
    "financialCategory": "Door Lock"
  },
  "hw-door-lock-stable-door-kit-type-1-bottom-sash": {
    "code": "DR-LCK-STABLE-DOOR-KIT-TYPE-1-BOTTOM-SASH",
    "name": "Stable Door Lock Kit Type#1 (Bottom Sash)",
    "cost": 0,
    "price": 0,
    "per": "pc",
    "weight": 0,
    "financialCategory": "Door Lock"
  },
  "hw-door-lock-stable-door-type-1-kit-top-sash": {
    "code": "DR-LCK-STABLE-DOOR-TYPE-1-KIT-TOP-SASH",
    "name": "Stable Door Lock Type#1 Kit (Top Sash)",
    "cost": 0,
    "price": 0,
    "per": "pc",
    "weight": 0,
    "financialCategory": "Door Lock"
  },
  "hw-door-lock-standard-slave-door": {
    "code": "DR-LCK-STANDARD-SLAVE-DOOR",
    "name": "Standard Slave Door Lock",
    "cost": 0,
    "price": 0,
    "per": "pc",
    "weight": 0,
    "financialCategory": "Door Lock"
  },
  "hw-handle-antique-black-l-h-monkeytail": {
    "code": "HDL-ANTIQUE-BLACK-L-H-MONKEYTAIL",
    "name": "Antique Black L/H Monkeytail Handle",
    "cost": 0,
    "price": 0,
    "per": "pc",
    "weight": 0,
    "financialCategory": "Casement Handles"
  },
  "hw-handle-antique-black-r-h-monkeytail": {
    "code": "HDL-ANTIQUE-BLACK-R-H-MONKEYTAIL",
    "name": "Antique Black R/H Monkeytail Handle",
    "cost": 0,
    "price": 0,
    "per": "pc",
    "weight": 0,
    "financialCategory": "Casement Handles"
  },
  "hw-handle-antique-bronze-l-h-monkeytail": {
    "code": "HDL-ANTIQUE-BRONZE-L-H-MONKEYTAIL",
    "name": "Antique Bronze L/H Monkeytail Handle",
    "cost": 0,
    "price": 0,
    "per": "pc",
    "weight": 0,
    "financialCategory": "Casement Handles"
  },
  "hw-handle-antique-bronze-r-h-monkeytail": {
    "code": "HDL-ANTIQUE-BRONZE-R-H-MONKEYTAIL",
    "name": "Antique Bronze R/H Monkeytail Handle",
    "cost": 0,
    "price": 0,
    "per": "pc",
    "weight": 0,
    "financialCategory": "Casement Handles"
  },
  "hw-handle-black-inline": {
    "code": "HDL-BLACK-INLINE",
    "name": "Black Inline Handle",
    "cost": 0,
    "price": 0,
    "per": "pc",
    "weight": 0,
    "financialCategory": "Casement Handles"
  },
  "hw-handle-black-l-h-cranked": {
    "code": "HDL-BLACK-L-H-CRANKED",
    "name": "Black L/H Cranked Handle",
    "cost": 0,
    "price": 0,
    "per": "pc",
    "weight": 0,
    "financialCategory": "Casement Handles"
  },
  "hw-handle-black-r-h-cranked": {
    "code": "HDL-BLACK-R-H-CRANKED",
    "name": "Black R/H Cranked Handle",
    "cost": 0,
    "price": 0,
    "per": "pc",
    "weight": 0,
    "financialCategory": "Casement Handles"
  },
  "hw-handle-bronze-inline": {
    "code": "HDL-BRONZE-INLINE",
    "name": "Bronze Inline Handle",
    "cost": 0,
    "price": 0,
    "per": "pc",
    "weight": 0,
    "financialCategory": "Casement Handles"
  },
  "hw-handle-bronze-l-h-cranked": {
    "code": "HDL-BRONZE-L-H-CRANKED",
    "name": "Bronze L/H Cranked Handle",
    "cost": 0,
    "price": 0,
    "per": "pc",
    "weight": 0,
    "financialCategory": "Casement Handles"
  },
  "hw-handle-bronze-r-h-cranked": {
    "code": "HDL-BRONZE-R-H-CRANKED",
    "name": "Bronze R/H Cranked Handle",
    "cost": 0,
    "price": 0,
    "per": "pc",
    "weight": 0,
    "financialCategory": "Casement Handles"
  },
  "hw-handle-chrome-inline": {
    "code": "HDL-CHROME-INLINE",
    "name": "Chrome Inline Handle",
    "cost": 0,
    "price": 0,
    "per": "pc",
    "weight": 0,
    "financialCategory": "Casement Handles"
  },
  "hw-handle-chrome-l-h-cranked": {
    "code": "HDL-CHROME-L-H-CRANKED",
    "name": "Chrome L/H Cranked Handle",
    "cost": 0,
    "price": 0,
    "per": "pc",
    "weight": 0,
    "financialCategory": "Casement Handles"
  },
  "hw-handle-chrome-l-h-monkeytail": {
    "code": "HDL-CHROME-L-H-MONKEYTAIL",
    "name": "Chrome L/H Monkeytail Handle",
    "cost": 0,
    "price": 0,
    "per": "pc",
    "weight": 0,
    "financialCategory": "Casement Handles"
  },
  "hw-handle-chrome-r-h-cranked": {
    "code": "HDL-CHROME-R-H-CRANKED",
    "name": "Chrome R/H Cranked Handle",
    "cost": 0,
    "price": 0,
    "per": "pc",
    "weight": 0,
    "financialCategory": "Casement Handles"
  },
  "hw-handle-chrome-r-h-monkeytail": {
    "code": "HDL-CHROME-R-H-MONKEYTAIL",
    "name": "Chrome R/H Monkeytail Handle",
    "cost": 0,
    "price": 0,
    "per": "pc",
    "weight": 0,
    "financialCategory": "Casement Handles"
  },
  "hw-handle-gold-inline": {
    "code": "HDL-GOLD-INLINE",
    "name": "Gold Inline Handle",
    "cost": 0,
    "price": 0,
    "per": "pc",
    "weight": 0,
    "financialCategory": "Casement Handles"
  },
  "hw-handle-gold-l-h-cranked": {
    "code": "HDL-GOLD-L-H-CRANKED",
    "name": "Gold L/H Cranked Handle",
    "cost": 0,
    "price": 0,
    "per": "pc",
    "weight": 0,
    "financialCategory": "Casement Handles"
  },
  "hw-handle-gold-l-h-monkeytail": {
    "code": "HDL-GOLD-L-H-MONKEYTAIL",
    "name": "Gold L/H Monkeytail Handle",
    "cost": 0,
    "price": 0,
    "per": "pc",
    "weight": 0,
    "financialCategory": "Casement Handles"
  },
  "hw-handle-gold-r-h-cranked": {
    "code": "HDL-GOLD-R-H-CRANKED",
    "name": "Gold R/H Cranked Handle",
    "cost": 0,
    "price": 0,
    "per": "pc",
    "weight": 0,
    "financialCategory": "Casement Handles"
  },
  "hw-handle-gold-r-h-monkeytail": {
    "code": "HDL-GOLD-R-H-MONKEYTAIL",
    "name": "Gold R/H Monkeytail Handle",
    "cost": 0,
    "price": 0,
    "per": "pc",
    "weight": 0,
    "financialCategory": "Casement Handles"
  },
  "hw-handle-graphite-inline": {
    "code": "HDL-GRAPHITE-INLINE",
    "name": "Graphite Inline Handle",
    "cost": 0,
    "price": 0,
    "per": "pc",
    "weight": 0,
    "financialCategory": "Casement Handles"
  },
  "hw-handle-graphite-l-h-cranked": {
    "code": "HDL-GRAPHITE-L-H-CRANKED",
    "name": "Graphite L/H Cranked Handle",
    "cost": 0,
    "price": 0,
    "per": "pc",
    "weight": 0,
    "financialCategory": "Casement Handles"
  },
  "hw-handle-graphite-l-h-monkeytail": {
    "code": "HDL-GRAPHITE-L-H-MONKEYTAIL",
    "name": "Graphite L/H Monkeytail Handle",
    "cost": 0,
    "price": 0,
    "per": "pc",
    "weight": 0,
    "financialCategory": "Casement Handles"
  },
  "hw-handle-graphite-r-h-cranked": {
    "code": "HDL-GRAPHITE-R-H-CRANKED",
    "name": "Graphite R/H Cranked Handle",
    "cost": 0,
    "price": 0,
    "per": "pc",
    "weight": 0,
    "financialCategory": "Casement Handles"
  },
  "hw-handle-graphite-r-h-monkeytail": {
    "code": "HDL-GRAPHITE-R-H-MONKEYTAIL",
    "name": "Graphite R/H Monkeytail Handle",
    "cost": 0,
    "price": 0,
    "per": "pc",
    "weight": 0,
    "financialCategory": "Casement Handles"
  },
  "hw-handle-silver-inline": {
    "code": "HDL-SILVER-INLINE",
    "name": "Silver Inline Handle",
    "cost": 0,
    "price": 0,
    "per": "pc",
    "weight": 0,
    "financialCategory": "Casement Handles"
  },
  "hw-handle-silver-l-h-cranked": {
    "code": "HDL-SILVER-L-H-CRANKED",
    "name": "Silver L/H Cranked Handle",
    "cost": 0,
    "price": 0,
    "per": "pc",
    "weight": 0,
    "financialCategory": "Casement Handles"
  },
  "hw-handle-silver-l-h-monkeytail": {
    "code": "HDL-SILVER-L-H-MONKEYTAIL",
    "name": "Silver L/H Monkeytail Handle",
    "cost": 0,
    "price": 0,
    "per": "pc",
    "weight": 0,
    "financialCategory": "Casement Handles"
  },
  "hw-handle-silver-r-h-cranked": {
    "code": "HDL-SILVER-R-H-CRANKED",
    "name": "Silver R/H Cranked Handle",
    "cost": 0,
    "price": 0,
    "per": "pc",
    "weight": 0,
    "financialCategory": "Casement Handles"
  },
  "hw-handle-silver-r-h-monkeytail": {
    "code": "HDL-SILVER-R-H-MONKEYTAIL",
    "name": "Silver R/H Monkeytail Handle",
    "cost": 0,
    "price": 0,
    "per": "pc",
    "weight": 0,
    "financialCategory": "Casement Handles"
  },
  "hw-handle-white-l-h-cranked": {
    "code": "HDL-WHITE-L-H-CRANKED",
    "name": "White L/H Cranked Handle",
    "cost": 0,
    "price": 0,
    "per": "pc",
    "weight": 0,
    "financialCategory": "Casement Handles"
  },
  "hw-handle-white-l-h-monkeytail": {
    "code": "HDL-WHITE-L-H-MONKEYTAIL",
    "name": "White L/H Monkeytail Handle",
    "cost": 0,
    "price": 0,
    "per": "pc",
    "weight": 0,
    "financialCategory": "Casement Handles"
  },
  "hw-handle-white-r-h-cranked": {
    "code": "HDL-WHITE-R-H-CRANKED",
    "name": "White R/H Cranked Handle",
    "cost": 0,
    "price": 0,
    "per": "pc",
    "weight": 0,
    "financialCategory": "Casement Handles"
  },
  "hw-handle-white-r-h-monkeytail": {
    "code": "HDL-WHITE-R-H-MONKEYTAIL",
    "name": "White R/H Monkeytail Handle",
    "cost": 0,
    "price": 0,
    "per": "pc",
    "weight": 0,
    "financialCategory": "Casement Handles"
  }
};
