-- This migration is intentionally empty.
--
-- The same schema changes were already included in:
--   20260627004703_initial
--
-- Keeping this folder as a no-op preserves the migration name for databases
-- that have already seen it while preventing duplicate-column failures on
-- fresh deploys.
